server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: data
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/character/**

eureka:
  client:
    register-with-eureka: false

